### ISSUE TITLE
Receiving addresses not showing rpc generate spark address 

### ISSUE THREAD

**Issue by mobias17** [firoorg/firo#1331] opened 2023-09-17 15:48 UTC
### Describe the issue

create a new spark address via `getnewsparkaddress `and funded the address.
![image](https://github.com/firoorg/firo/assets/48771525/6e820f1c-8594-403b-8b50-1debfd8819e8)

new address neither in receiving tab nor in receiving addresses.
![image](https://github.com/firoorg/firo/assets/48771525/3042c0be-fc43-4f76-b782-9d3a9c5cbdcb)

Comparing this to transparent address
created new address and funded it via faucet
![image](https://github.com/firoorg/firo/assets/48771525/35274cb8-41ff-41bd-91e4-4ebe00e05802)

new address not in receiving tab but in receiving addresses.
![image](https://github.com/firoorg/firo/assets/48771525/9f8343d1-9ec6-4015-af7c-be93c04dd225)

might need evaluation whether bug / feature / works as designed.

### local setup
Ubuntu 18.04
![image](https://github.com/firoorg/firo/assets/48771525/7b343560-2395-4e90-bab9-855f05f7cf52)

**Comment by justanwar** [comment] 2023-09-18 09:10
Duplicate of #1288 (already fixed)

**Closed by justanwar** 2023-09-18 09:10 UTC
